//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employee.Data
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JqueryDataTableDBEntities : DbContext
    {
        public JqueryDataTableDBEntities()
            : base("name=JqueryDataTableDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EmployeeTable> EmployeeTable { get; set; }
        public virtual DbSet<SalaryTable> SalaryTable { get; set; }
        public virtual DbSet<UserMaster> UserMaster { get; set; }
        public IEnumerable<object> EmployeeModel { get; set; }
    }
}
