//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employee.Data
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class EmployeeTable
    {
        public string yes { get; set; }
        public int Id { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public string Designation { get; set; }
        public string city { get; set; }
        public int? salary { get; set; }
        //[Required]
        public string Image { get; set; }
        public HttpPostedFileBase file { get; set; }
        public int? SalaryId { get; set; }

        //[Required]
        public string Email { get; set; }
        public string no { get; set; }
        public virtual SalaryTable SalaryTable { get; set; }
    }
}
